spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost/ratings
    username: root
    driver-class-name: com.mysql.jdbc.Driver

security:
  basic:
    enabled: false

---

spring:
  profiles: default
  jpa:
    database: MYSQL

---

spring:
  profiles: cloud
  jpa:
    database: MYSQL

security:
  basic:
    enabled: false