server:
  port: 9000

security:

  user:
    password: password

zuul:
  routes:
    springbox-catalog: /catalog/**
    springbox-reviews: /reviews/**
    springbox-recommendations: /recommendations/**
    user:
      path: /user/**
      url: http://auth-server.pcf1.fe.gopivotal.com/uaa/user

spring:
  oauth2:
    sso:
      home:
        secure: false
        path: /,/**/*.html
    client:
      accessTokenUri: https://auth-server.pcf1.fe.gopivotal.com/uaa/oauth/token
      userAuthorizationUri: https://auth-server.pcf1.fe.gopivotal.com/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      userInfoUri: https://auth-server.pcf1.fe.gopivotal.com/uaa/user


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.netflix: INFO
    com.netflix.zuul: DEBUG
    io.springbox.apigateway: DEBUG
    org.apache.http.client: DEBUG
