server:
  port: 8081

security:
  basic:
    enabled: false
management:
  security:
    enabled: false

logging.level.org.springframework.security: DEBUG
---
spring:
  profiles: default
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost/springbox-movies
    username: root
    driver-class-name: com.mysql.jdbc.Driver
---
spring:
  profiles: cloud
  jpa:
    database: MYSQL