server:
  port: 9000
ribbon:
  IsSecure: false

security:
  basic:
    enabled: false
management:
  security:
    enabled: false
zuul:
  routes:
    springbox-catalog: /catalog/**
    springbox-reviews: /reviews/**
    springbox-recommendations: /recommendations/**

