server:
  port: 8082
spring:
  oauth2:
    resource:
      userInfoUri: ${vcap.services.auth-server.credentials.uri:http://localhost:9999/uaa/user}
logging:
  logging:
    org.springframework.web: DEBUG
    io.springbox.recommendations: DEBUG